/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.utp.isc.progiv.p4.clase20.ui.gui;

import co.edu.utp.isc.progiv.p4.clase20.ui.gui.estudiante.PnlEstudiante;
import java.awt.CardLayout;
import java.awt.Cursor;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author cdiaz
 */
public class FrmUniversidad extends javax.swing.JFrame {

    /**
     * Creates new form FrmUniversidad
     */
    public FrmUniversidad() {
        initComponents();
        iniciarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu1 = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu2 = new javax.swing.JMenu();
        miEstudiantes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestión Universitaria");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, "clean");

        jMenu1.setText("Archivo");

        miSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        jMenu1.add(miSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventanas");

        miEstudiantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miEstudiantes.setText("Estudiantes");
        miEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEstudiantesActionPerformed(evt);
            }
        });
        jMenu2.add(miEstudiantes);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrarFormulario();
    }//GEN-LAST:event_formWindowClosing

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        cerrarFormulario();
    }//GEN-LAST:event_miSalirActionPerformed

    private void miEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEstudiantesActionPerformed
        mostrarPanel("estudiante");
    }//GEN-LAST:event_miEstudiantesActionPerformed

    public static void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmUniversidad().setVisible(true);
        });
    }

    private void iniciarFormulario() {
        setSize(800, 600);
        setLocationRelativeTo(null);
    }

    private void cerrarFormulario() throws HeadlessException {
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro en salir?", getTitle(), JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {
            dispose();
        }
    }

    private void mostrarPanel(String panel) {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        switch (panel) {
            case "estudiante":
                if (pnlEstudiante == null) {
                    pnlEstudiante = new PnlEstudiante(getTitle());
                    getContentPane().add(pnlEstudiante, panel);
                }
                ((CardLayout) getContentPane().getLayout()).show(getContentPane(), panel);
                break;
            default:
                throw new AssertionError();
        }
        setCursor(Cursor.getDefaultCursor());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem miEstudiantes;
    private javax.swing.JMenuItem miSalir;
    // End of variables declaration//GEN-END:variables
    private PnlEstudiante pnlEstudiante = null;

}
