/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.utp.isc.progiv.p4.clase20.ui.gui;

import co.edu.utp.isc.progiv.p4.clase20.excepciones.BaseDatosException;
import co.edu.utp.isc.progiv.p4.clase20.excepciones.NoEncontradoException;
import co.edu.utp.isc.progiv.p4.clase20.logica.UniversidadFacade;
import javax.swing.JOptionPane;

/**
 *
 * @author cdiaz
 */
public class PnlCurso extends javax.swing.JPanel {

    /**
     * Creates new form PnlCurso
     */
    public PnlCurso() {
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Prueba"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Hola");
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {
        try {
            var facade = new UniversidadFacade();
            var cursos = facade.listarCursos();
            jTextArea1.setText("");
            cursos.forEach(curso -> {
                System.out.println(curso);
                jTextArea1.setText(jTextArea1.getText() + curso + "\n");
            });
        } catch (BaseDatosException | NoEncontradoException ex) {
            JOptionPane.showMessageDialog(this, "Error cargando datos\n" + ex.getMessage());
        }
    }
}
